-- ===========================================================================
-- The six role scorecards, seeded from Documents/DTG/KPI/Role.
--
-- Generated from backend/app/data/kpi_role_templates.json rather than retyped,
-- so the weights and wording match the role documents exactly. Re-runnable:
-- templates are matched on  and their items replaced.
-- ===========================================================================

begin;

-- Geotechnical Monitoring Engineer -- 10 KPIs, weights total 100
insert into public.kpi_role_templates (code, title, version, source_document, bands)
values ('monitoring_engineer', 'Geotechnical Monitoring Engineer', '2026', 'Monitoring_Engineer_KPI_2026.docx', '[''60% Safety judgement & response'', ''25% Delivery & data quality'', ''15% Learning, improvement & teamwork'']')
on conflict (code) do update
   set title = excluded.title,
       source_document = excluded.source_document,
       bands = excluded.bands,
       updated_at = now();

delete from public.kpi_template_items where template_id = (select id from public.kpi_role_templates where code = 'monitoring_engineer');
insert into public.kpi_template_items (template_id, number, category, name, weight, target, how_measured, evidence, sort_order) values
  ((select id from public.kpi_role_templates where code = 'monitoring_engineer'), '01', 'SAFETY & JUDGEMENT', 'Severity-weighted detection performance', 20.0, 'Zero Critical misses. Weighted miss score within the agreed team threshold, normalised per 100 shift-days.', 'Σ (severity points × attributable misses) ÷ shift-days × 100. Low 1; Medium 4; High 10; Critical 25. A self-reported miss, raised before anyone else identifies it, counts at 50%.', 'Miss register; quarterly back-test; client query log; first-detectable epoch; roster.', 0),
  ((select id from public.kpi_role_templates where code = 'monitoring_engineer'), '02', 'SAFETY & JUDGEMENT', 'Interpretation accuracy', 15.0, '≥90% agreement in quarterly blind review; no unresolved High/Critical interpretation error.', 'A senior reviewer re-analyses a random sample of about 10 report-days without seeing the original commentary. Compare trend class, likely cause, threshold judgement and recommendation.', 'Blind-audit worksheet; sampled radar plots; reviewer conclusion; action log.', 1),
  ((select id from public.kpi_role_templates where code = 'monitoring_engineer'), '03', 'RESPONSE', 'TARP response compliance', 15.0, '≥95% compliant events; 100% for Critical triggers; zero Critical breach.', 'An event passes only if the correct action tier was completed within the site TARP window and receipt/acknowledgement was closed. Score against the information reasonably available at the time.', 'TARP; trigger log; call/email timestamps; named acknowledgement; escalation record.', 2),
  ((select id from public.kpi_role_templates where code = 'monitoring_engineer'), '04', 'RESPONSE', 'Alarm disposition and communication', 10.0, '100% of alarms dispositioned; ≥95% within the local SLA; 100% of genuine alarms communicated as required.', 'Every alarm is recorded as genuine, suspected artefact or under review. Suppressed alarms require an internal record and cause code. The site SLA supplies the actual response minutes.', 'Alarm register; sent email/call record; graph snapshot; cause code; shift log.', 3),
  ((select id from public.kpi_role_templates where code = 'monitoring_engineer'), '05', 'DELIVERY & QUALITY', 'Monitoring report delivery', 10.0, '≥98% issued on time; 100% include the required plots, trend conclusion, exceedances and recommended action.', 'On-time, complete reports ÷ reports due. Exclude approved outages or late upstream data when the dependency was escalated promptly.', 'Report register; issued files; submission timestamps; dependency/escalation log.', 4),
  ((select id from public.kpi_role_templates where code = 'monitoring_engineer'), '06', 'DELIVERY & QUALITY', 'Report accuracy and reissue rate', 10.0, '<2% engineer-attributable reissues; zero material error left uncorrected after discovery.', 'Cause-coded engineer-attributable reissues ÷ reports issued. Do not count client scope change, upstream data correction, template change or approved technical reinterpretation.', 'Version history; reissue request; cause code; corrective action.', 5),
  ((select id from public.kpi_role_templates where code = 'monitoring_engineer'), '07', 'DELIVERY & QUALITY', 'Proactive data-quality control', 5.0, '≥90% of attributable data issues identified internally before client escalation.', 'Issues originating during the engineer’s shifts that they identified first ÷ all issues originating during those shifts. Attribute to the first epoch at which the issue was detectable.', 'Data-issue log; client correspondence; meeting minutes; first-detectable epoch.', 6),
  ((select id from public.kpi_role_templates where code = 'monitoring_engineer'), '08', 'LEARNING FROM EVENTS', 'Post-event / fall-of-ground analysis', 5.0, '100% completed where assigned; ≥90% within 14 days or the contractually agreed window; independent precursor review completed.', 'Use the site event register as the denominator. Each review covers precursor, detectability, instrumentation adequacy and recommended change. If there are no events, rate at team level or mark N/A and reallocate the weight.', 'Site FoG/event register; signed analysis; independent review; action tracker.', 7),
  ((select id from public.kpi_role_templates where code = 'monitoring_engineer'), '09', 'IMPROVEMENT', 'Practical improvement and procedure contribution', 5.0, '≥2 quality-assessed improvement proposals per year and ≥1 meaningful procedure update per year.', 'Count only proposals that define the problem, proposed change, expected benefit, risk and test approach. Score submission and sound analysis; approval depends on management and is not required.', 'Improvement register; trial result; SOP revision history; reviewer decision.', 8),
  ((select id from public.kpi_role_templates where code = 'monitoring_engineer'), '10', 'RELIABILITY & TEAMWORK', 'Handover and professional behaviour', 5.0, '100% required handovers complete; behaviour rating ≥3/5 with written examples.', 'Handover covers open alarms, data issues, pending client actions and unusual conditions. Twice-yearly rating by manager plus one peer, anchored to responsiveness, knowledge sharing and escalation judgement.', 'Handover log; action closure; manager and peer examples; coaching record.', 9);

-- Underground Monitoring Engineer -- 10 KPIs, weights total 100
insert into public.kpi_role_templates (code, title, version, source_document, bands)
values ('underground_monitoring', 'Underground Monitoring Engineer', '2026', 'Underground_Monitoring_KPI_2026.docx', '[''45% Technical quality'', ''35% Delivery, records & risk'', ''15% Initiative & execution'', ''5% Safety & teamwork'']')
on conflict (code) do update
   set title = excluded.title,
       source_document = excluded.source_document,
       bands = excluded.bands,
       updated_at = now();

delete from public.kpi_template_items where template_id = (select id from public.kpi_role_templates where code = 'underground_monitoring');
insert into public.kpi_template_items (template_id, number, category, name, weight, target, how_measured, evidence, sort_order) values
  ((select id from public.kpi_role_templates where code = 'underground_monitoring'), '01', 'TECHNICAL QUALITY', 'Data processing accuracy and specification compliance', 20.0, '≥98% of processed datasets pass the agreed validation criteria before release; zero Critical processing error.', 'Compliant datasets ÷ datasets completed. Validate coordinate system, units, registration/alignment, control or checkpoints, coverage, classification, scale and required derivatives against the project specification.', 'Processing log; project specification; control/checkpoint results; alignment statistics; reviewer sign-off.', 0),
  ((select id from public.kpi_role_templates where code = 'underground_monitoring'), '02', 'TECHNICAL QUALITY', 'QA/QC execution and audit conformity', 15.0, '100% of Critical checks and ≥98% of all required QA/QC checks completed before release; ≥95% internal audit conformity.', 'Required checks completed correctly and on time ÷ required checks. Use the approved checklist and retain the result, tolerance, reviewer and corrective action.', 'QA/QC checklist; audit sample; error log; corrective-action closure; reviewer record.', 1),
  ((select id from public.kpi_role_templates where code = 'underground_monitoring'), '03', 'DELIVERY', 'On-time data and project deliverables', 12.0, '≥95% delivered by the agreed deadline, after approved dependency exclusions.', 'On-time accepted deliverables ÷ deliverables due. Exclude late source data, site-access constraints or system outages only when recorded and escalated before the deadline risk became unavoidable.', 'Delivery register; project plan; issue timestamp; dependency and escalation log.', 2),
  ((select id from public.kpi_role_templates where code = 'underground_monitoring'), '04', 'TECHNICAL QUALITY', 'First-pass acceptance and rework', 10.0, '≥95% accepted at first technical review; engineer-attributable material rework <2%.', 'Deliverables accepted without material correction ÷ deliverables reviewed. Rework must be cause-coded; scope change and corrected upstream data do not count against the employee.', 'Review comments; revision history; rework cause code; acceptance record.', 3),
  ((select id from public.kpi_role_templates where code = 'underground_monitoring'), '05', 'DATA STEWARDSHIP', 'Database, metadata and file integrity', 8.0, '≥98% records complete and compliant; zero lost, overwritten or unrecoverable project data.', 'Check naming, folder structure, metadata, version control, processing history, archive location and restoration/retrieval. Score only items within the employee’s access and responsibility.', 'Database audit; file manifest; metadata record; version history; archive/retrieval test.', 4),
  ((select id from public.kpi_role_templates where code = 'underground_monitoring'), '06', 'RISK CONTROL', 'Anomaly identification and escalation', 8.0, '100% of material anomalies escalated within the agreed SLA; ≥90% identified internally before client or senior-review escalation.', 'Track data gaps, registration drift, inconsistent scans, improbable deformation, corrupted files and processing failures. Attribute an issue to the point when it was first reasonably detectable.', 'Anomaly register; processing log; message/call timestamp; first-detectable point; reviewer classification.', 5),
  ((select id from public.kpi_role_templates where code = 'underground_monitoring'), '07', 'REPORTING', 'Monitoring reports and technical documentation', 7.0, '≥95% accepted without material correction and delivered on time; 100% traceable to source data and processing version.', 'Assess required content, figures, methods, limitations, result summary, file references and consistency between the report and processed dataset.', 'Report register; technical review; source-file link; issue record; revision history.', 6),
  ((select id from public.kpi_role_templates where code = 'underground_monitoring'), '08', 'INITIATIVE', 'Quality of improvement ideas', 7.0, '≥1 quality-assessed idea per half-year.', 'A qualifying idea states the problem, evidence, proposed change, expected benefit, risk and test approach. Quality matters more than quantity; suggestions without analysis do not count.', 'Improvement register; short proposal; reviewer assessment; proposed test plan.', 7),
  ((select id from public.kpi_role_templates where code = 'underground_monitoring'), '09', 'INITIATIVE', 'Execution of improvement or automation', 8.0, '≥1 tested improvement, prototype or automation contribution per half-year.', 'Score problem definition, test quality, documentation, handover and measured effect on time, error risk, consistency or usability. Management approval is not required if a safe test/prototype is completed.', 'Before/after measure; code or workflow; test result; documentation; handover or demonstration.', 8),
  ((select id from public.kpi_role_templates where code = 'underground_monitoring'), '10', 'RELIABILITY', 'Collaboration, learning and safe work practices', 5.0, 'Anchored behaviour rating ≥3/5; mandatory safety, information-security and quality requirements met.', 'Use written examples from the manager and one project colleague. Consider responsiveness, learning, communication, care with shared data, following controls and asking for help at the right time.', 'Manager/peer examples; training record; safety or quality observations; coaching and action closure.', 9);

-- IT / Software Developer -- 10 KPIs, weights total 100
insert into public.kpi_role_templates (code, title, version, source_document, bands)
values ('it_software_developer', 'IT / Software Developer', '2026', 'IT_Software_Developer_KPI_2026.docx', '[''40% Software & platform'', ''27% Support & connectivity'', ''20% Infrastructure & security'', ''10% Process & improvement'', ''3% Advice & ownership'']')
on conflict (code) do update
   set title = excluded.title,
       source_document = excluded.source_document,
       bands = excluded.bands,
       updated_at = now();

delete from public.kpi_template_items where template_id = (select id from public.kpi_role_templates where code = 'it_software_developer');
insert into public.kpi_template_items (template_id, number, category, name, weight, target, how_measured, evidence, sort_order) values
  ((select id from public.kpi_role_templates where code = 'it_software_developer'), '01', 'SOFTWARE DELIVERY DTG', 'DTG Focus and digital-solution delivery', 18.0, '≥90% of committed milestones accepted within the agreed release window; scope changes recorded before the due date.', 'Accepted roadmap or project milestones ÷ milestones committed for the period. A milestone counts when acceptance criteria, user outcome, release notes and required handover are complete.', 'Approved roadmap; ticket/issue; acceptance criteria; release record; stakeholder sign-off.', 0),
  ((select id from public.kpi_role_templates where code = 'it_software_developer'), '02', 'SOFTWARE QUALITY', 'Code quality, testing and secure development', 12.0, '100% production changes reviewed and tested; ≥95% required test checks passed; zero knowingly released Critical defect or vulnerability.', 'Check peer/technical review, functional and regression testing, security checks, error handling and rollback readiness. Use project-appropriate controls; do not reward test quantity without coverage of material risk.', 'Pull request/review; test results; vulnerability finding; release checklist; rollback plan.', 1),
  ((select id from public.kpi_role_templates where code = 'it_software_developer'), '03', 'PLATFORM RELIABILITY DTG', 'DTG Focus maintenance and service reliability', 10.0, '≥99% availability in the agreed service window; ≥95% defects/incidents resolved within SLA; planned maintenance communicated.', 'Use monitored availability and cause-coded incidents. Exclude approved maintenance and external dependencies after timely escalation. Track restoration, root cause and recurrence prevention.', 'Availability monitor; incident record; deployment log; root-cause action; maintenance notice.', 2),
  ((select id from public.kpi_role_templates where code = 'it_software_developer'), '04', 'ICT SUPPORT', 'Service Desk response and resolution', 12.0, '≥95% tickets acknowledged within SLA; ≥90% resolved within SLA; 100% Critical incidents acknowledged and escalated.', 'Calculate from complete ticket records by priority. Paused time requires a documented dependency, user wait or vendor wait. Reopened tickets are reviewed for resolution quality.', 'Service Desk export; priority/SLA matrix; timestamps; escalation and closure notes.', 3),
  ((select id from public.kpi_role_templates where code = 'it_software_developer'), '05', 'MONITORING CONTINUITY', 'Remote client-site connectivity support', 15.0, '100% assigned connections monitored/administered; ≥95% connectivity incidents actioned within SLA; 100% Critical loss escalated.', 'Assess TeamViewer/approved management-console administration, device status, authorized access, incident response, recovery and handover. Client network or carrier downtime is excluded after prompt escalation.', 'Management-console log; connection inventory; alert/ticket; client/vendor escalation; recovery record.', 4),
  ((select id from public.kpi_role_templates where code = 'it_software_developer'), '06', 'INFRASTRUCTURE', 'Server, network and endpoint administration', 10.0, '≥95% scheduled administration tasks completed on time; 100% production changes authorized and recorded; zero avoidable Critical outage.', 'Measure assigned server, network, endpoint, asset and configuration work against approved schedules and change records. Include health checks and recurring-fault actions.', 'Maintenance schedule; configuration/change record; asset register; monitoring alert; closure evidence.', 5),
  ((select id from public.kpi_role_templates where code = 'it_software_developer'), '07', 'SECURITY & RESILIENCE', 'Access, patching, backup and security control compliance', 10.0, '100% privileged access reviewed; 100% Critical patches/actions within approved window; backup jobs monitored and restoration tests completed as scheduled.', 'Score only assigned controls. Track MFA/privileged access, patch exceptions, endpoint protection, backup failures, restoration evidence and incident escalation. Approved exceptions must name an owner and due date.', 'Access review; patch report; backup log; restoration test; security alert; exception register.', 6),
  ((select id from public.kpi_role_templates where code = 'it_software_developer'), '08', 'PROCESS CONTROL', 'Documentation, change and knowledge management', 5.0, '≥95% required records current; 100% material changes and recurring fixes documented within the agreed window.', 'Review system diagrams, asset/configuration records, runbooks, code/release notes, admin procedures and known-error articles. Documentation must allow another authorized person to operate or recover the service.', 'Runbook; change record; architecture/system note; knowledge article; review history.', 7),
  ((select id from public.kpi_role_templates where code = 'it_software_developer'), '09', 'IMPROVEMENT', 'Automation and improvement initiative', 5.0, '≥2 quality-assessed improvement proposals per year, with ≥1 safely tested or delivered.', 'A qualifying improvement defines the problem, evidence, proposed change, risk, test, rollback and expected benefit. Score the quality and execution; production adoption requires approval.', 'Improvement register; script/tool/prototype; before/after result; test and rollback record; handover.', 8),
  ((select id from public.kpi_role_templates where code = 'it_software_developer'), '10', 'RELIABILITY', 'Technical advice, collaboration and ownership', 3.0, 'Anchored behaviour rating ≥3/5 with written examples; required training, security and professional controls met.', 'Manager plus one user/project colleague assess communication, prioritisation, technical advice, escalation judgement, handover, learning and follow-through. Use evidence, not popularity.', 'Manager/peer examples; user feedback; meeting/action record; training; coaching closure.', 9);

-- Business & Technical Support -- 10 KPIs, weights total 100
insert into public.kpi_role_templates (code, title, version, source_document, bands)
values ('business_technical_support', 'Business & Technical Support', '2026', 'Business_Technical_Support_KPI_2026.docx', '[''30% Finance'', ''20% Reporting & client'', ''20% People & records'', ''18% Technical & operations'', ''12% Coordination & improvement'']')
on conflict (code) do update
   set title = excluded.title,
       source_document = excluded.source_document,
       bands = excluded.bands,
       updated_at = now();

delete from public.kpi_template_items where template_id = (select id from public.kpi_role_templates where code = 'business_technical_support');
insert into public.kpi_template_items (template_id, number, category, name, weight, target, how_measured, evidence, sort_order) values
  ((select id from public.kpi_role_templates where code = 'business_technical_support'), '01', null, 'Reconciliations and expense records', 15.0, '100% monthly bank, credit-card and travel reconciliations completed by the agreed close date; ≥98% items matched correctly; all unresolved differences logged and escalated within 2 business days.', 'Use the approved Xero and source-document checklist. Accuracy is verified by reviewer sampling. Exclude late statements or approvals after timely follow-up.', 'Reconciliation report; statement; receipt/invoice; exception log; reviewer sign-off. Timely, supported reconciliations keep management information reliable and make unusual transactions visible.', 0),
  ((select id from public.kpi_role_templates where code = 'business_technical_support'), '02', null, 'Accounts payable, receivable and invoicing', 15.0, '≥98% authorised invoices prepared by the due date; 100% use approved customer, contract, rate and tax information; overdue and payable registers reviewed monthly; zero unauthorised payment approval.', 'Measure preparation, record quality, follow-up and escalation. Payment approval and commercial rate approval remain with authorised management. Indonesian invoices remain with the designated Indonesian entity unless reassigned in writing.', 'Invoice register; approved instruction/contract; aged receivables/payables; follow-up record; approval trail. Accurate billing supports cash flow, while clear approval boundaries reduce error and fraud risk.', 1),
  ((select id from public.kpi_role_templates where code = 'business_technical_support'), '03', null, 'Monthly reporting and action follow-up', 10.0, '100% monthly management pack prepared by the agreed cut-off; 100% material actions have an owner and due date; ≥95% follow-ups issued on time.', 'Check completeness of finance inputs, HR summary, action register and exceptions. The employee follows up; action owners remain accountable for completing their work.', 'Monthly pack; action register; meeting minutes; reminder/escalation record. A concise, timely pack helps management act before small finance, people or operational issues become larger problems.', 2),
  ((select id from public.kpi_role_templates where code = 'business_technical_support'), '04', null, 'Client records, onboarding and sales-pipeline administration', 10.0, '100% new client folders and checklists created when authorised; client register and sales pipeline updated monthly; ≥95% approved changes recorded within 2 business days.', 'Review required fields, version control, contact data and handover readiness. Commercial decisions, pricing and sales conversion are not individual KPI outcomes.', 'Client register; onboarding checklist; CRM/pipeline; folder audit; approval or handover record. Reliable client records reduce missed commitments and allow operational and commercial teams to work from the same information.', 3),
  ((select id from public.kpi_role_templates where code = 'business_technical_support'), '05', null, 'HR administration and employee lifecycle records', 10.0, '100% assigned onboarding and offboarding checklists completed by the agreed date; required HR procedures kept current; monthly HR issues summary complete and confidential.', 'Score administration, access coordination, document completion and escalation. Hiring, termination, remuneration and policy approval remain authorised management decisions.', 'Onboarding/offboarding checklist; HR procedure; access request/closure; issue summary; approval record. Complete, confidential lifecycle records protect employees and help the business meet its employment obligations.', 4),
  ((select id from public.kpi_role_templates where code = 'business_technical_support'), '06', null, 'Document control, NAS organisation and confidentiality', 10.0, '≥95% sampled files correctly named, located and current; 100% confidential records stored with approved access; zero avoidable confidentiality breach.', 'Quarterly sample of finance, HR, client and vendor folders. Approved retention rules apply; duplicate or obsolete files are archived or escalated, not deleted without authority.', 'Folder audit; access list; naming/index guide; archive record; privacy/security incident log. Good document control makes work findable and auditable while protecting employee, client and commercial information.', 5),
  ((select id from public.kpi_role_templates where code = 'business_technical_support'), '07', null, 'Authorised backup monitoring and technical support', 10.0, '100% assigned backup alerts checked and recorded; 100% failed or missed backups escalated within the agreed window; ≥95% support requests actioned within SLA.', 'Assess authorised checks, first-response troubleshooting, user communication, escalation and closure evidence. Do not score underlying system uptime when the employee does not control the fix.', 'Backup console/log; alert record; support ticket; escalation; recovery or closure confirmation. Early detection and clear escalation protect continuity without extending the role beyond authorised technical access.', 6),
  ((select id from public.kpi_role_templates where code = 'business_technical_support'), '08', null, 'Vendor, compliance and office administration', 8.0, 'Vendor and office registers current; 100% known expiry, certification or maintenance risks escalated before the agreed lead time; ≥95% scheduled office tasks completed on time.', 'Cover vendor files/logs, Kurloo follow-up, office maintenance, cleaning schedule and assigned task lists. Exclude supplier or management delays after timely follow-up.', 'Vendor register; compliance tracker; communication log; maintenance/cleaning record; escalation. Structured follow-up prevents avoidable expiry, supplier and office-service gaps.', 7),
  ((select id from public.kpi_role_templates where code = 'business_technical_support'), '09', null, 'Communication, scheduling and dependable follow-through', 7.0, '≥95% assigned meeting notes and actions issued within 1 business day; ≥95% committed coordination tasks completed or escalated before the due date; behaviour rating ≥3/5 with examples.', 'Manager plus one internal stakeholder assess clarity, discretion, prioritisation, handover and follow-through. Do not use popularity or availability outside agreed hours.', 'Calendar/minutes; task log; handover; stakeholder example; escalation record. This combined support role succeeds when people receive clear information and commitments do not disappear between teams.', 8),
  ((select id from public.kpi_role_templates where code = 'business_technical_support'), '10', null, 'Process improvement and initiative', 5.0, '≥2 quality-assessed improvement proposals per year, with ≥1 safely tested, documented or delivered.', 'A qualifying proposal identifies the problem, evidence, expected benefit, risk, approval path and handover. Production or policy changes require approval.', 'Improvement register; revised checklist/template; trial result; before/after evidence; approval/handover. Practical initiative should reduce repeated administration, errors and follow-up effort without encouraging uncontrolled change.', 9);

-- Acting Director / Technical Lead -- 10 KPIs, weights total 100
insert into public.kpi_role_templates (code, title, version, source_document, bands)
values ('acting_director_technical_lead', 'Acting Director / Technical Lead', '2026', 'Acting_Director_Technical_Lead_KPI_2026.docx', '[''25% Director & corporate'', ''15% Technical assurance'', ''25% DTG Focus & UCM'', ''10% Kurloo'', ''25% Leadership, operations & people'']')
on conflict (code) do update
   set title = excluded.title,
       source_document = excluded.source_document,
       bands = excluded.bands,
       updated_at = now();

delete from public.kpi_template_items where template_id = (select id from public.kpi_role_templates where code = 'acting_director_technical_lead');
insert into public.kpi_template_items (template_id, number, category, name, weight, target, how_measured, evidence, sort_order) values
  ((select id from public.kpi_role_templates where code = 'acting_director_technical_lead'), '01', null, 'Governance and Reserved Authorities compliance', 15.0, '100% reserved matters submitted for approval before commitment; 100% material conflicts disclosed; zero unauthorised material commitment or document execution.', 'Test decisions and signatures against the approved Reserved Authorities Matrix, articles, shareholder instructions and applicable law. Record advice, approval, conflict and execution evidence.', 'Decision/approval register; board or shareholder resolution; conflict disclosure; signed-document register. The Acting Director must keep local operations moving without taking decisions reserved to shareholders.', 0),
  ((select id from public.kpi_role_templates where code = 'acting_director_technical_lead'), '02', null, 'Indonesian corporate, regulatory and banking support', 10.0, '100% known filings, licences, banking and administrative actions completed or escalated before the agreed due date; obligations register reviewed monthly.', 'Score preparation, local coordination, document execution within authority, follow-up and escalation. Exclude authority or agency delay after complete and timely submission.', 'Obligations register; OSS/licence record; bank correspondence; filing receipt; adviser instruction. The appointment exists partly so the Indonesian entity can meet local operational and corporate requirements.', 1),
  ((select id from public.kpi_role_templates where code = 'acting_director_technical_lead'), '03', null, 'Business leadership and shareholder reporting', 10.0, 'Monthly operating dashboard delivered by the agreed date; 100% material risks, decisions and overdue actions visible; ≥95% leadership commitments completed or escalated on time.', 'Review concise reporting on people, projects, finance, clients, compliance, risks and decisions required. Shareholders remain accountable for reserved decisions.', 'Monthly dashboard; risk/action register; decision paper; meeting record; escalation. Good local leadership gives shareholders enough reliable information to decide without taking over daily operations.', 2),
  ((select id from public.kpi_role_templates where code = 'acting_director_technical_lead'), '04', null, 'Technical governance and engineering assurance', 15.0, '100% designated technical deliverables reviewed through the approved process; zero knowingly accepted Critical technical nonconformance; ≥95% review actions closed by due date.', 'Define design/review authority, acceptance criteria, independent checks and deviation approval. Score assurance and decisions, not the volume of engineering personally completed.', 'Design/review record; calculation or model check; technical decision; deviation/NCR; action closure. The Lead Engineer protects technical quality and safety by creating a defensible review and sign-off chain.', 3),
  ((select id from public.kpi_role_templates where code = 'acting_director_technical_lead'), '05', null, 'DTG Focus roadmap, delivery and reliability', 15.0, '≥90% committed roadmap milestones accepted in the agreed release window; 100% production releases reviewed, tested and documented; material incidents actioned within SLA.', 'Use quarterly approved scope and acceptance criteria. Record scope change before the due date. Include release quality, operational reliability, recovery and stakeholder acceptance.', 'Roadmap; issue/PR; test and release record; acceptance; incident/root-cause action. DTG Focus must produce reliable user value, not simply code output or development activity.', 4),
  ((select id from public.kpi_role_templates where code = 'acting_director_technical_lead'), '06', 'UCM / DTG', 'UCM / DTG Focus development delivery', 10.0, '≥90% committed UCM milestones accepted; 100% material integrations and data changes tested; zero knowingly released Critical defect or security vulnerability.', 'Assess working features, integration/data quality, secure review, documentation and handover. Rebaseline dependencies and discovery work before the deadline.', 'Backlog/milestone; architecture note; code review; tests; demo/acceptance; deployment record. UCM development needs its own evidence so it is not hidden inside broader DTG Focus responsibilities.', 5),
  ((select id from public.kpi_role_templates where code = 'acting_director_technical_lead'), '07', null, 'Kurloo project delivery and compliance', 10.0, '≥95% agreed Kurloo actions and deliverables completed or escalated on time; 100% certification, vendor or client compliance risks recorded before due date.', 'Use the approved project plan, responsibility matrix and compliance tracker. Exclude third-party delay after timely follow-up and complete inputs.', 'Project plan; compliance tracker; vendor/client correspondence; deliverable acceptance; risk/escalation. Kurloo combines project, partner and compliance work and therefore needs a visible delivery outcome.', 6),
  ((select id from public.kpi_role_templates where code = 'acting_director_technical_lead'), '08', null, 'Client and operational technical leadership', 5.0, '100% Critical client or operational technical risks acknowledged and escalated within the agreed window; ≥95% assigned decisions or support actions completed within SLA.', 'Score prioritisation, technical judgement, communication, recovery support and closure. Do not transfer every operational task to the senior role.', 'Incident/support record; technical advice; client communication; decision and closure log. Senior intervention should resolve high-risk issues while preserving clear ownership in the operating teams.', 7),
  ((select id from public.kpi_role_templates where code = 'acting_director_technical_lead'), '09', null, 'Team leadership, delegation and capability', 5.0, 'Objectives and decision rights agreed for all direct reports; quarterly coaching completed; at least one competent backup identified for each critical technical or operational area.', 'Review delegation, feedback, workload, training, succession coverage and whether work is owned at the appropriate level. Do not reward doing the team’s work personally.', 'Role/objective record; one-to-one notes; capability matrix; delegation or handover; development action. A combined Director and Technical Lead role is sustainable only when capability and authority are distributed.', 8),
  ((select id from public.kpi_role_templates where code = 'acting_director_technical_lead'), '10', null, 'Strategy, improvement and transition readiness', 5.0, 'Quarterly priorities and capacity allocation approved; ≥2 quality-assessed improvement proposals per year with ≥1 delivered; Acting Director transition/handover record kept current.', 'Connect improvements to risk, client value, efficiency or scale. Maintain an orderly handover for a future General Manager, Country Manager or other approved structure.', 'Priority/capacity plan; improvement case; before/after result; transition pack; knowledge handover. The interim appointment should strengthen the business and make future leadership changes easier, not create dependency.', 9);

-- Finance & Administration Assistant -- 10 KPIs, weights total 100
insert into public.kpi_role_templates (code, title, version, source_document, bands)
values ('finance_administration_assistant', 'Finance & Administration Assistant', '2026', 'Finance_Administration_Assistant_KPI_2026.docx', '[''30% Compliance & records'', ''22% Payroll & cash'', ''20% Budget & reporting'', ''16% Transactions & people'', ''12% Office & improvement'']')
on conflict (code) do update
   set title = excluded.title,
       source_document = excluded.source_document,
       bands = excluded.bands,
       updated_at = now();

delete from public.kpi_template_items where template_id = (select id from public.kpi_role_templates where code = 'finance_administration_assistant');
insert into public.kpi_template_items (template_id, number, category, name, weight, target, how_measured, evidence, sort_order) values
  ((select id from public.kpi_role_templates where code = 'finance_administration_assistant'), '01', null, 'Statutory, tax and government reporting compliance', 15.0, '100% statutory and tax calendar maintained; assigned returns and supporting schedules prepared by the agreed internal deadline; zero employee-controlled late filing or penalty; known risk escalated at least 5 business days before the statutory due date.', 'Assess preparation, completeness, deadline control, evidence and escalation. Final tax interpretation, signing and filing approval remain with the authorised director, accountant or tax adviser.', 'Compliance calendar; tax workpaper; submission receipt; adviser correspondence; approval and exception log. Timely, supported reporting protects the Indonesian business from avoidable penalties and regulatory disruption.', 0),
  ((select id from public.kpi_role_templates where code = 'finance_administration_assistant'), '02', null, 'Bookkeeping and general ledger accuracy', 15.0, '100% assigned transactions posted by the monthly close date; ≥98% sampled coding and supporting-document accuracy; all unexplained or suspense items investigated and escalated within 5 business days.', 'Monthly reviewer sample of ledger entries, journals, supporting documents and correction history. Exclude missing source documents after timely follow-up.', 'General ledger; journal list; document sample; correction log; reviewer sign-off. Accurate books support reliable tax returns, management reporting, budgeting and audit readiness.', 1),
  ((select id from public.kpi_role_templates where code = 'finance_administration_assistant'), '03', null, 'Payroll accuracy, timeliness and confidentiality', 12.0, '100% payroll inputs prepared by the agreed cut-off; ≥99.5% employee-data and calculation accuracy; corrections or anomalies escalated within 1 business day; zero avoidable confidentiality breach.', 'Compare approved employee data, attendance/leave inputs, payroll output and payment instruction. Approval and release of payroll remain with authorised management.', 'Payroll checklist; approved employee changes; variance review; payment approval; correction and confidentiality record. Payroll is a high-trust process affecting employee welfare, statutory obligations and confidence in management.', 2),
  ((select id from public.kpi_role_templates where code = 'finance_administration_assistant'), '04', null, 'Bank and cash reconciliation and control', 10.0, '100% bank accounts and petty cash reconciled by the agreed monthly close; ≥98% items matched correctly; material differences escalated within 2 business days; zero unauthorised banking or payment instruction.', 'Use statements, ledger and approved cash records. Bank-detail changes require independent verification and delegated approval.', 'Bank reconciliation; petty-cash count; statement; exception log; approval and bank-change verification. Regular reconciliation makes errors and unusual transactions visible while protecting company cash.', 3),
  ((select id from public.kpi_role_templates where code = 'finance_administration_assistant'), '05', null, 'Budget preparation and forecast support', 10.0, 'Annual budget and assigned forecast updates completed by the agreed date; 100% material assumptions traceable to an approved source; ≥95% first-pass completeness with no material formula error.', 'Score preparation quality, traceability and review responsiveness—not business outcomes or management assumptions outside the employee’s control.', 'Budget workbook; assumptions register; source schedules; review comments; version and approval record. A controlled budget gives management a realistic basis for staffing, project and cash decisions.', 4),
  ((select id from public.kpi_role_templates where code = 'finance_administration_assistant'), '06', null, 'Budget tracking and management reporting', 10.0, 'Monthly budget-versus-actual report issued by the agreed close date; 100% material variances have a documented cause, owner or escalation; ≥98% sampled report accuracy.', 'Compare report to the ledger and approved budget. Separate employee preparation from decisions or actions owned by management.', 'Monthly management pack; variance analysis; action log; ledger tie-out; reviewer sign-off. Timely variance reporting lets management respond before cash, cost or delivery issues grow.', 5),
  ((select id from public.kpi_role_templates where code = 'finance_administration_assistant'), '07', null, 'Payables, receivables, invoicing and banking administration', 10.0, '≥98% authorised invoices and payment packs prepared by their due date; aged receivables/payables reviewed monthly; 100% use approved supplier, customer, rate, tax and bank data; zero independent approval of own work.', 'Review timeliness, source evidence, register quality, follow-up and segregation of duties. Payment release and commercial approval remain authorised decisions.', 'Invoice and payable registers; aged balances; approved contract/instruction; bank verification; approval trail. Accurate transaction administration supports cash flow and prevents avoidable error or fraud.', 6),
  ((select id from public.kpi_role_templates where code = 'finance_administration_assistant'), '08', null, 'Employee onboarding and welfare administration', 6.0, '100% assigned onboarding, payroll, welfare and social-security actions completed or escalated by the agreed date; employee records current and confidential; welfare issues acknowledged within 1 business day.', 'Score checklist completion, coordination, confidentiality and escalation. Hiring, remuneration, disciplinary and benefit-policy decisions remain with management.', 'Onboarding checklist; employee master-data update; BPJS or welfare record; access coordination; issue log. Reliable onboarding and welfare administration helps employees become productive and supports compliance.', 7),
  ((select id from public.kpi_role_templates where code = 'finance_administration_assistant'), '09', null, 'Office, premises and contractor administration', 7.0, '≥95% scheduled office, cleaning and maintenance activities completed on time; 100% identified safety, repair or service risks logged and escalated within 1 business day; contractors engaged only with approval.', 'Review premises checks, maintenance register, contractor scope, completion evidence and cost approval. Exclude vendor delays after timely follow-up.', 'Maintenance and cleaning register; photographs; contractor quotation/work order; approval; completion and escalation record. A safe, clean and maintained workplace supports employees and protects business continuity.', 8),
  ((select id from public.kpi_role_templates where code = 'finance_administration_assistant'), '10', null, 'Administrative support, IT coordination and process improvement', 5.0, '≥95% assigned administrative or IT-support requests completed or escalated within the agreed time; ≥2 sound improvement proposals per year, with ≥1 approved improvement tested, documented or delivered.', 'Score request tracking, communication, safe coordination and practical benefit. Technical changes must be performed or approved by authorised IT support.', 'Task or ticket register; IT service request; communication record; improvement proposal; test and handover evidence. Dependable coordination and practical initiative reduce repeated administrative effort without encouraging uncontrolled system changes.', 9);

commit;

-- Every template must total 100, or a scorecard rated 3 throughout will not
-- come to 100 and every band downstream is wrong.
select t.code, count(*) as items, sum(i.weight) as total_weight
  from public.kpi_role_templates t
  join public.kpi_template_items i on i.template_id = t.id
 group by t.code order by t.code;
